import { test } from "node:test";
import assert from "node:assert/strict";
import { FlightSession } from "../src/flight-session";
import { defaultFlightConfig } from "../src/physics";
import { createAircraft, aircraftOptions } from "../src/fleet";
import { getAirport, airportTerrain } from "../src/airports";
const terrain = (x: number, z = 0) => airportTerrain(x, z, 0);
test("selection starts each aircraft parked on the first runway and waits for pilot input", () => {
    const airport = getAirport(0);
    for (const { id } of aircraftOptions) {
        const session = new FlightSession({ ...defaultFlightConfig }, terrain);
        const before = structuredClone(session.state);
        session.step(1, 10);
        assert.deepEqual(session.state, before);
        session.select(createAircraft(id));
        assert.equal(session.waiting, false);
        assert.equal(session.state.phase, 'parked');
        assert.equal(session.state.distance, airport.start + 8);
        assert.equal(session.state.altitude, airport.elevation + session.config.groundClearance);
        session.step(0, 1);
        assert.equal(session.state.distance, airport.start + 8);
        assert.equal(session.state.horizontalSpeed, 0);
        session.step(1, 3.5);
        assert.equal(session.state.phase, 'flying', id);
        assert.ok(session.state.altitude > airport.elevation + session.config.groundClearance);
    }
});
test("crash resets pause before movement then chosen aircraft parks on a safe next runway", () => {
    const session = new FlightSession({ ...defaultFlightConfig }, terrain);
    session.select(createAircraft('military'));
    session.state.phase = 'flying';
    session.state.distance = getAirport(0).end + 25;
    session.state.altitude = .1;
    session.state.velocity = -4;
    session.step(0, 1 / 120);
    assert.equal(session.state.phase, 'crashed');
    session.step(1, 10);
    assert.equal(session.waiting, true);
    assert.equal(session.state.phase, 'flying');
    const after = structuredClone(session.state);
    session.step(-1, 5);
    assert.deepEqual(session.state, after);
    session.select(createAircraft('transport'));
    assert.equal(session.waiting, false);
    assert.equal(session.state.phase, 'parked');
    assert.equal(session.state.distance, getAirport(1).start + 8);
    assert.equal(session.state.velocity, 0);
    assert.equal(session.state.horizontalSpeed, 0);
    assert.equal(session.state.crashBody, null);
    const distance = session.state.distance;
    session.step(0, 1);
    assert.equal(session.state.distance, distance);
});
test("selection clears aerobatics and ignores half-roll requests while parked or waiting", () => {
    const session = new FlightSession({ ...defaultFlightConfig }, terrain);
    session.step(1, 1, true);
    assert.equal(session.state.rollActive, false);
    session.select(createAircraft('cessna'));
    session.step(0, .3, true);
    assert.equal(session.state.rollActive, false);
    session.state.phase = 'flying';
    session.state.altitude = 20;
    session.state.horizontalSpeed = 11;
    session.step(0, .3, true);
    assert.equal(session.state.rollActive, true);
    session.state.pitchVelocity = 1;
    session.select(createAircraft('passenger'));
    assert.equal(session.state.roll, 0);
    assert.equal(session.state.pitch, 0);
    assert.equal(session.state.pitchVelocity, 0);
    assert.equal(session.state.phase, 'parked');
});
test("a reset while over an airport reuses that runway with enough takeoff distance", () => {
    const session = new FlightSession({ ...defaultFlightConfig }, terrain);
    session.state.distance = getAirport(2).start + 30;
    session.select(createAircraft('passenger'));
    assert.equal(session.state.distance, getAirport(2).start + 8);
    session.step(1, 3.5);
    assert.equal(session.state.phase, 'flying');
});
